# Generated by Django 6.0.2 on 2026-04-07 13:11

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Avatar')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Birth Date')),
                ('currency', models.CharField(choices=[('EUR', 'EUR – Euro'), ('USD', 'USD – US Dollar'), ('GBP', 'GBP – British Pound'), ('CHF', 'CHF – Swiss Franc'), ('JPY', 'JPY – Japanese Yen'), ('CNY', 'CNY – Chinese Yuan'), ('AUD', 'AUD – Australian Dollar'), ('CAD', 'CAD – Canadian Dollar'), ('NZD', 'NZD – New Zealand Dollar'), ('SEK', 'SEK – Swedish Krona'), ('NOK', 'NOK – Norwegian Krone'), ('DKK', 'DKK – Danish Krone'), ('PLN', 'PLN – Polish Zloty'), ('CZK', 'CZK – Czech Koruna'), ('TRY', 'TRY – Turkish Lira'), ('INR', 'INR – Indian Rupee'), ('BRL', 'BRL – Brazilian Real'), ('ZAR', 'ZAR – South African Rand')], default='EUR', max_length=3, verbose_name='Currency')),
                ('language', models.CharField(choices=[('de', 'Deutsch'), ('en', 'English'), ('fr', 'Français'), ('es', 'Español'), ('it', 'Italiano')], default='de', max_length=10, verbose_name='Language')),
                ('simulation_max_age', models.PositiveIntegerField(default=90, verbose_name='Simulation Max Age')),
                ('inflation_rate', models.DecimalField(decimal_places=2, default=2.0, max_digits=5, verbose_name='Default Inflation Rate (%)')),
                ('salary_increase', models.DecimalField(decimal_places=2, default=1.5, max_digits=5, verbose_name='Default Salary Increase (%)')),
                ('pension_increase', models.DecimalField(decimal_places=2, default=1.0, max_digits=5, verbose_name='Default Pension Increase (%)')),
                ('investment_return_offset', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Investment Return Offset (%)')),
                ('real_estate_growth_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Default Real Estate Growth (%)')),
                ('physical_asset_growth_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Default Physical Asset Growth (%)')),
                ('dashboard_config', models.JSONField(blank=True, default=dict, verbose_name='Dashboard Configuration')),
                ('gradient_start', models.CharField(default='#6610f2', max_length=7, verbose_name='Gradient Start Color')),
                ('gradient_end', models.CharField(default='#0d6efd', max_length=7, verbose_name='Gradient End Color')),
                ('primary_color', models.CharField(default='#0d6efd', max_length=7, verbose_name='Primary Color')),
                ('secondary_color', models.CharField(default='#6c757d', max_length=7, verbose_name='Secondary Color')),
                ('background_color', models.CharField(default='#ffffff', max_length=7, verbose_name='Background Color')),
                ('text_color', models.CharField(default='#212529', max_length=7, verbose_name='Text Color')),
                ('sidebar_bg_color', models.CharField(default='#f8f9fa', max_length=7, verbose_name='Sidebar Background')),
                ('table_header_bg_color', models.CharField(default='#212529', max_length=7, verbose_name='Table Header Background')),
                ('table_header_text_color', models.CharField(default='#ffffff', max_length=7, verbose_name='Table Header Text')),
                ('table_filter_bg_color', models.CharField(default='#f1f3f5', max_length=7, verbose_name='Table Filter Background')),
                ('table_body_bg_color', models.CharField(default='#ffffff', max_length=7, verbose_name='Table Body Background')),
                ('table_body_text_color', models.CharField(default='#212529', max_length=7, verbose_name='Table Body Text')),
                ('table_border_color', models.CharField(default='#dee2e6', max_length=7, verbose_name='Table Border Color')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
            },
        ),
    ]
