# Generated by Django 6.0.2 on 2026-04-08 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='auto_night_mode',
            field=models.BooleanField(default=False, verbose_name='Follow System Design'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='dark_mode_config',
            field=models.JSONField(blank=True, default=dict, verbose_name='Night Mode Colors'),
        ),
    ]
