# Generated by Django 6.0.2 on 2026-02-15 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='inflation_rate',
            field=models.DecimalField(decimal_places=2, default=2.0, max_digits=5, verbose_name='Default Inflation Rate (%)'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='investment_return_offset',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Investment Return Offset (%)'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='salary_growth',
            field=models.DecimalField(decimal_places=2, default=1.5, max_digits=5, verbose_name='Default Salary Growth (%)'),
        ),
    ]
