# Generated by Django 6.0.2

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_userprofile_auto_night_mode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='dark_mode_config',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='Night Mode Colors'),
        ),
    ]
