# Generated by Django 6.0.2 on 2026-02-15 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_userprofile_inflation_rate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='salary_growth',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='salary_increase',
            field=models.DecimalField(decimal_places=2, default=1.5, max_digits=5, verbose_name='Default Salary Increase (%)'),
        ),
    ]
