# Generated by Django 6.0.2 on 2026-03-27 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_userprofile_salary_growth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='currency',
            field=models.CharField(choices=[('EUR', 'EUR – Euro'), ('USD', 'USD – US Dollar'), ('GBP', 'GBP – British Pound'), ('CHF', 'CHF – Swiss Franc'), ('JPY', 'JPY – Japanese Yen'), ('CNY', 'CNY – Chinese Yuan'), ('AUD', 'AUD – Australian Dollar'), ('CAD', 'CAD – Canadian Dollar'), ('NZD', 'NZD – New Zealand Dollar'), ('SEK', 'SEK – Swedish Krona'), ('NOK', 'NOK – Norwegian Krone'), ('DKK', 'DKK – Danish Krone'), ('PLN', 'PLN – Polish Zloty'), ('CZK', 'CZK – Czech Koruna'), ('TRY', 'TRY – Turkish Lira'), ('INR', 'INR – Indian Rupee'), ('BRL', 'BRL – Brazilian Real'), ('ZAR', 'ZAR – South African Rand')], default='EUR', max_length=3, verbose_name='Currency'),
        ),
    ]
