# Generated by Django 6.0.2 on 2026-04-09 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_manual_fix_null_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='display_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Anzeigename'),
        ),
    ]
