# Generated by Django 6.0.2 on 2026-04-09 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_userprofile_display_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='display_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Display Name'),
        ),
    ]
