# Generated by Django 6.0.2 on 2026-03-28 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_userprofile_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='table_filter_bg_color',
            field=models.CharField(default='#f1f3f5', max_length=7, verbose_name='Table Filter Background'),
        ),
        migrations.AddField(
            model_name='theme',
            name='table_header_bg_color',
            field=models.CharField(default='#212529', max_length=7, verbose_name='Table Header Background'),
        ),
        migrations.AddField(
            model_name='theme',
            name='table_header_text_color',
            field=models.CharField(default='#ffffff', max_length=7, verbose_name='Table Header Text'),
        ),
    ]
