# Generated by Django 6.0.2 on 2026-04-02 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_theme_table_filter_bg_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='table_body_bg_color',
            field=models.CharField(default='#ffffff', max_length=7, verbose_name='Table Body Background'),
        ),
        migrations.AddField(
            model_name='theme',
            name='table_body_text_color',
            field=models.CharField(default='#212529', max_length=7, verbose_name='Table Body Text'),
        ),
        migrations.AddField(
            model_name='theme',
            name='table_border_color',
            field=models.CharField(default='#dee2e6', max_length=7, verbose_name='Table Border Color'),
        ),
    ]
