# Generated by Django 6.0.2 on 2026-05-04 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_userprofile_display_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='simulation_start_date',
            field=models.DateField(blank=True, help_text='Earliest date to show in charts. Leave empty for automatic (based on oldest snapshot or current year).', null=True, verbose_name='Simulation Start Date'),
        ),
    ]
