# Generated by Django 6.0.2 on 2026-05-04 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_userprofile_simulation_start_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='physical_asset_growth_rate',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='investment_return_offset',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Investment Return Buffer (%)'),
        ),
    ]
