# Generated by Django 6.0.2 on 2026-04-02 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_theme_table_body_bg_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='gradient_end',
            field=models.CharField(default='#0d6efd', help_text='Hex color for gradient end (e.g. #0d6efd)', max_length=7, verbose_name='Gradient End Color'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='gradient_start',
            field=models.CharField(default='#6610f2', help_text='Hex color for gradient start (e.g. #6610f2)', max_length=7, verbose_name='Gradient Start Color'),
        ),
    ]
