# Generated by Django 6.0.2 on 2026-04-03 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_add_gradient_to_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='gradient_end',
            field=models.CharField(default='#0d6efd', max_length=7, verbose_name='Gradient End Color'),
        ),
        migrations.AddField(
            model_name='theme',
            name='gradient_start',
            field=models.CharField(default='#6610f2', max_length=7, verbose_name='Gradient Start Color'),
        ),
    ]
