# Generated by Django 6.0.2 on 2026-04-07 13:11

import django.contrib.auth.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='Slug')),
                ('color', models.CharField(default='#6c757d', help_text='Hex color code, e.g. #FF0000', max_length=7, verbose_name='Color')),
                ('is_system', models.BooleanField(default=False, verbose_name='System Category')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='FinancialStatusProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Mein Finanzstatus (Vorausgefüllt)',
                'verbose_name_plural': 'Meine Finanzen (Schnelleingabe)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.customuser',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('value', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Current Value')),
                ('growth_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Annual Growth Rate (%)')),
                ('withdrawal_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Amount to take out of this asset each month', max_digits=12, verbose_name='Monthly Withdrawal')),
                ('withdrawal_start_date', models.DateField(blank=True, null=True, verbose_name='Withdrawal Start Date')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Asset',
                'verbose_name_plural': 'Assets',
            },
        ),
        migrations.CreateModel(
            name='CashFlowSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('value', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Amount')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Start Date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='End Date')),
                ('is_income', models.BooleanField(default=True, verbose_name='Is Income')),
                ('is_inflation_adjusted', models.BooleanField(default=True, help_text='If checked, the payout will increase annually based on the global pension increase rate.', verbose_name='Indexed (Inflation Adjustment)')),
                ('frequency', models.CharField(choices=[('monthly', 'Monthly'), ('yearly', 'Yearly')], default='monthly', max_length=20, verbose_name='Frequency')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cash_flows', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.category', verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Cash Flow Source',
                'verbose_name_plural': 'Cash Flow Sources',
            },
        ),
        migrations.CreateModel(
            name='ImportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('filename', models.CharField(max_length=255)),
                ('is_applied', models.BooleanField(default=False)),
                ('ai_log', models.TextField(blank=True, null=True, verbose_name='AI Log / Errors')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_batches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Import Batch',
                'verbose_name_plural': 'Import Batches',
            },
        ),
        migrations.CreateModel(
            name='ImportFilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_query', models.CharField(help_text='Separated by semicolon, e.g. EDEKA;REWE', max_length=255, verbose_name='Search Query')),
                ('target_name', models.CharField(help_text='e.g. Lebensmitteleinkäufe', max_length=100, verbose_name='Target Name')),
                ('is_income', models.BooleanField(default=False, verbose_name='Is Income')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.category', verbose_name='Category')),
                ('linked_cash_flow', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_filters', to='finance.cashflowsource', verbose_name='Linked Cash Flow Source')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_filters', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Import Filter',
                'verbose_name_plural': 'Import Filters',
            },
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('provider', models.CharField(blank=True, max_length=100, verbose_name='Provider / Bank')),
                ('nominal_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Initial Loan Amount')),
                ('interest_rate', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Interest Rate (%)')),
                ('interest_lock_end', models.DateField(blank=True, null=True, verbose_name='Interest Lock End Date')),
                ('monthly_installment', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monthly Installment')),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='End Date')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('allows_extra_repayment', models.BooleanField(default=False, verbose_name='Extra Repayment Possible')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Loan / Debt',
                'verbose_name_plural': 'Loans / Debts',
            },
        ),
        migrations.CreateModel(
            name='LoanExtraRepayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Amount')),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_repayments', to='finance.loan')),
            ],
            options={
                'verbose_name': 'Extra Repayment',
                'verbose_name_plural': 'Extra Repayments',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='OneTimeEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('value', models.DecimalField(decimal_places=2, help_text='Positive for income, negative for expense', max_digits=12, verbose_name='Amount')),
                ('date', models.DateField(verbose_name='Date')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'One Time Event',
                'verbose_name_plural': 'One Time Events',
            },
        ),
        migrations.CreateModel(
            name='PendingTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('description', models.TextField(verbose_name='Description')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Amount')),
                ('is_income', models.BooleanField(default=True, verbose_name='Is Income')),
                ('planned_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Planned Amount')),
                ('is_recurring', models.BooleanField(default=False, verbose_name='Is Recurring')),
                ('frequency', models.CharField(choices=[('monthly', 'Monthly'), ('yearly', 'Yearly')], default='monthly', max_length=20, verbose_name='Frequency')),
                ('ai_reasoning', models.TextField(blank=True, null=True, verbose_name='AI Reasoning')),
                ('is_ignored', models.BooleanField(default=False, verbose_name='Ignore')),
                ('matched_terms', models.TextField(blank=True, null=True, verbose_name='Matched Terms (Notes)')),
                ('integration_count', models.IntegerField(default=1, verbose_name='Integration Count')),
                ('signature', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Transaction Signature')),
                ('has_conflict', models.BooleanField(default=False, verbose_name='Has Plan Conflict')),
                ('is_confirmed', models.BooleanField(default=False, verbose_name='Confirmed Conflict')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='finance.importbatch')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.category', verbose_name='Suggested Category')),
                ('existing_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conflicting_transactions', to='finance.cashflowsource')),
            ],
            options={
                'verbose_name': 'Pending Transaction',
                'verbose_name_plural': 'Pending Transactions',
            },
        ),
        migrations.CreateModel(
            name='Pension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=100, verbose_name='Provider/Name')),
                ('current_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Current Value')),
                ('monthly_contribution', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Monthly Contribution')),
                ('growth_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Annual Growth Rate (%)')),
                ('expected_payout_at_retirement', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Expected Monthly Payout')),
                ('is_indexed', models.BooleanField(default=True, help_text='If checked, the payout will increase annually based on the global pension increase rate.', verbose_name='Indexed (Inflation Adjustment)')),
                ('contribution_end_date', models.DateField(blank=True, help_text='Date when you stop paying into this pension', null=True, verbose_name='Contribution End Date')),
                ('start_payout_date', models.DateField(blank=True, help_text='Approximate date when pension payout starts', null=True, verbose_name='Payout Start Date')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pensions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pension',
                'verbose_name_plural': 'Pensions',
            },
        ),
        migrations.CreateModel(
            name='PhysicalAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('value', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Current Value')),
                ('appreciation_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Annual Appreciation Rate (%)')),
                ('location', models.CharField(blank=True, max_length=255, verbose_name='Location / Storage')),
                ('storage_costs_monthly', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Monthly Storage/Maintenance Costs')),
                ('is_sold', models.BooleanField(default=False, verbose_name='Is Sold')),
                ('sale_date', models.DateField(blank=True, null=True, verbose_name='Sale Date')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='physical_assets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sachwert (Physical Asset)',
                'verbose_name_plural': 'Sachwerte (Physical Assets)',
            },
        ),
        migrations.CreateModel(
            name='RealEstate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name / Property')),
                ('property_value', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Property Value')),
                ('appreciation_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Annual Appreciation Rate (%)')),
                ('location', models.CharField(blank=True, max_length=255, verbose_name='Location')),
                ('current_tenant', models.CharField(blank=True, max_length=100, verbose_name='Current Tenant')),
                ('rental_income_monthly', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Monthly Rental Income (Net)')),
                ('maintenance_costs_monthly', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Monthly Maintenance/Mgmt Costs')),
                ('ancillary_costs_monthly', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Monthly Ancillary Costs (Nebenkosten)')),
                ('is_sold', models.BooleanField(default=False, verbose_name='Is Sold')),
                ('sale_date', models.DateField(blank=True, null=True, verbose_name='Sale Date')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='real_estates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Immobilie (Real Estate)',
                'verbose_name_plural': 'Immobilien (Real Estate)',
            },
        ),
    ]
