# Generated by Django 6.0.2 on 2026-04-07 20:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='importbatch',
            name='file_hash',
            field=models.CharField(blank=True, db_index=True, max_length=128, null=True),
        ),
        migrations.CreateModel(
            name='ProcessedTransactionHash',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash', models.CharField(db_index=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='row_hashes', to='finance.importbatch')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processed_hashes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Processed Transaction Hash',
                'verbose_name_plural': 'Processed Transaction Hashes',
                'unique_together': {('user', 'hash')},
            },
        ),
    ]
