# Generated by Django 6.0.2 on 2026-02-15 13:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=100, verbose_name='Provider/Name')),
                ('current_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Current Value')),
                ('monthly_contribution', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Monthly Contribution')),
                ('growth_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Annual Growth Rate (%)')),
                ('expected_payout_at_retirement', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Expected Monthly Payout')),
                ('start_payout_date', models.DateField(blank=True, help_text='Approximate date when pension payout starts', null=True, verbose_name='Payout Start Date')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pensions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pension',
                'verbose_name_plural': 'Pensions',
            },
        ),
    ]
