# Generated by Django 6.0.2 on 2026-03-27 10:11

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_userprofile_currency'),
        ('finance', '0002_pension'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialStatusProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Mein Finanzstatus (Vorausgefüllt)',
                'verbose_name_plural': 'Meine Finanzen (Schnelleingabe)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.customuser',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
