# Generated by Django 6.0.2 on 2026-04-07 21:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_importbatch_file_hash_processedtransactionhash'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='importfilter',
            constraint=models.UniqueConstraint(condition=models.Q(('category__isnull', False)), fields=('user', 'category'), name='unique_filter_per_category'),
        ),
    ]
