# Generated by Django 6.0.2 on 2026-03-27 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_financialstatusproxy'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='withdrawal_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Amount to take out of this asset each month', max_digits=12, verbose_name='Monthly Withdrawal'),
        ),
        migrations.AddField(
            model_name='asset',
            name='withdrawal_start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Withdrawal Start Date'),
        ),
    ]
