# Generated by Django 6.0.2 on 2026-04-08 13:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_pendingtransaction_raw_signatures'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingtransaction',
            name='ai_confidence',
            field=models.FloatField(default=1.0, help_text='0.0 to 1.0', verbose_name='AI Confidence'),
        ),
        migrations.CreateModel(
            name='CategorizationMemory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255, verbose_name='Description')),
                ('last_used', models.DateTimeField(auto_now=True)),
                ('usage_count', models.PositiveIntegerField(default=1)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.category', verbose_name='Category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cat_memories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Categorization Memory',
                'verbose_name_plural': 'Categorization Memories',
                'constraints': [models.UniqueConstraint(fields=('user', 'description'), name='unique_memory_per_desc')],
            },
        ),
    ]
