# Generated by Django 6.0.2 manually on 2026-04-02 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_importbatch_pendingtransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingtransaction',
            name='ai_reasoning',
            field=models.TextField(blank=True, null=True, verbose_name='AI Reasoning'),
        ),
    ]
