# Generated by Django 6.0.2 manually on 2026-04-02 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_pendingtransaction_ai_reasoning'),
    ]

    operations = [
        migrations.AddField(
            model_name='importbatch',
            name='ai_log',
            field=models.TextField(blank=True, null=True, verbose_name='AI Log / Errors'),
        ),
    ]
