# Generated by Django 6.0.2 on 2026-04-28 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_asset_interest_teaser_rate_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='financialstatusproxy',
            options={'verbose_name': 'My Financial Status', 'verbose_name_plural': 'My Finances (Quick Entry)'},
        ),
        migrations.AlterModelOptions(
            name='physicalasset',
            options={'verbose_name': 'Physical Asset', 'verbose_name_plural': 'Physical Assets'},
        ),
        migrations.AlterModelOptions(
            name='realestate',
            options={'verbose_name': 'Real Estate', 'verbose_name_plural': 'Real Estates'},
        ),
    ]
