# Generated by Django 6.0.2 on 2026-05-04 07:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('finance', '0008_realestate_acquisition_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('date', models.DateField(verbose_name='Date')),
                ('value', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Value')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_snapshots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Asset Snapshot',
                'verbose_name_plural': 'Asset Snapshots',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='finance_ass_content_4ecaeb_idx'), models.Index(fields=['date'], name='finance_ass_date_14b8a6_idx')],
            },
        ),
    ]
