# Generated by Django 6.0.2 on 2026-04-04 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0008_alter_category_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='pension',
            name='contribution_end_date',
            field=models.DateField(blank=True, help_text='Date when you stop paying into this pension', null=True, verbose_name='Contribution End Date'),
        ),
    ]
