# Generated by Django 6.0.2 on 2026-04-04 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0009_pension_contribution_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='pension',
            name='is_indexed',
            field=models.BooleanField(default=True, help_text='If checked, the payout will increase annually based on the global pension increase rate.', verbose_name='Indexed (Inflation Adjustment)'),
        ),
    ]
