# Generated by Django 6.0.2 on 2026-05-04 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0009_assetsnapshot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Display Name'),
        ),
        migrations.AlterField(
            model_name='cashflowsource',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Display Name'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Display Name'),
        ),
        migrations.AlterField(
            model_name='importfilter',
            name='target_name',
            field=models.CharField(help_text='e.g. Grocery shopping', max_length=100, verbose_name='Target Name'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Display Name'),
        ),
        migrations.AlterField(
            model_name='loanextrarepayment',
            name='date',
            field=models.DateField(verbose_name='Entry Date'),
        ),
        migrations.AlterField(
            model_name='onetimeevent',
            name='date',
            field=models.DateField(verbose_name='Entry Date'),
        ),
        migrations.AlterField(
            model_name='onetimeevent',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Display Name'),
        ),
        migrations.AlterField(
            model_name='pendingtransaction',
            name='date',
            field=models.DateField(verbose_name='Entry Date'),
        ),
        migrations.AlterField(
            model_name='physicalasset',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Display Name'),
        ),
        migrations.AlterField(
            model_name='realestate',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Provider / Name'),
        ),
    ]
