# Generated by Django 6.0.2 on 2026-04-04 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0010_pension_is_indexed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashflowsource',
            name='is_inflation_adjusted',
            field=models.BooleanField(default=True, help_text='If checked, the payout will increase annually based on the global pension increase rate.', verbose_name='Indexed (Inflation Adjustment)'),
        ),
    ]
