# Generated by Django 6.0.2 on 2026-05-05 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0010_alter_asset_name_alter_cashflowsource_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assetsnapshot',
            options={'ordering': ['-date'], 'verbose_name': 'Historical Data', 'verbose_name_plural': 'Historical Data'},
        ),
    ]
