# Generated by Django 6.0.2 on 2026-04-05 09:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0011_alter_cashflowsource_is_inflation_adjusted'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PhysicalAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('value', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Current Value')),
                ('appreciation_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Annual Appreciation Rate (%)')),
                ('location', models.CharField(blank=True, max_length=255, verbose_name='Location / Storage')),
                ('storage_costs_monthly', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Monthly Storage/Maintenance Costs')),
                ('is_sold', models.BooleanField(default=False, verbose_name='Is Sold')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='physical_assets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sachwert (Physical Asset)',
                'verbose_name_plural': 'Sachwerte (Physical Assets)',
            },
        ),
        migrations.CreateModel(
            name='RealEstate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name / Property')),
                ('property_value', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Property Value')),
                ('appreciation_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Annual Appreciation Rate (%)')),
                ('location', models.CharField(blank=True, max_length=255, verbose_name='Location')),
                ('current_tenant', models.CharField(blank=True, max_length=100, verbose_name='Current Tenant')),
                ('rental_income_monthly', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Monthly Rental Income (Net)')),
                ('maintenance_costs_monthly', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Monthly Maintenance/Mgmt Costs')),
                ('ancillary_costs_monthly', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Monthly Ancillary Costs (Nebenkosten)')),
                ('is_sold', models.BooleanField(default=False, verbose_name='Is Sold')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='real_estates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Immobilie (Real Estate)',
                'verbose_name_plural': 'Immobilien (Real Estate)',
            },
        ),
    ]
