# Generated by Django 6.0.2 on 2026-05-05 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0011_alter_assetsnapshot_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='physicalasset',
            name='acquisition_date',
            field=models.DateField(blank=True, null=True, verbose_name='Acquisition Date'),
        ),
    ]
