# Generated by Django 6.0.2 on 2026-04-05 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0012_physicalasset_realestate'),
    ]

    operations = [
        migrations.AddField(
            model_name='physicalasset',
            name='sale_date',
            field=models.DateField(blank=True, null=True, verbose_name='Sale Date'),
        ),
        migrations.AddField(
            model_name='realestate',
            name='sale_date',
            field=models.DateField(blank=True, null=True, verbose_name='Sale Date'),
        ),
    ]
