# Generated by Django 6.0.2 on 2026-05-05 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0012_physicalasset_acquisition_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='pension',
            name='contribution_start_date',
            field=models.DateField(blank=True, help_text='Date when you started paying into this pension', null=True, verbose_name='Contribution Start Date'),
        ),
    ]
