# Generated by manually (Simulating Django's makemigrations)
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finance', '0015_category_is_system'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportFilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_query', models.CharField(help_text='Separated by semicolon, e.g. EDEKA;REWE', max_length=255, verbose_name='Search Query')),
                ('target_name', models.CharField(help_text='e.g. Lebensmitteleinkäufe', max_length=100, verbose_name='Target Name')),
                ('is_income', models.BooleanField(default=False, verbose_name='Is Income')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.category', verbose_name='Category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_filters', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Import Filter',
                'verbose_name_plural': 'Import Filters',
            },
        ),
    ]
