# Generated by Django 6.0.2 on 2026-04-07 09:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0018_plan_reconciliation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingtransaction',
            name='existing_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conflicting_transactions', to='finance.cashflowsource'),
        ),
        migrations.AddField(
            model_name='pendingtransaction',
            name='has_conflict',
            field=models.BooleanField(default=False, verbose_name='Has Plan Conflict'),
        ),
        migrations.AddField(
            model_name='pendingtransaction',
            name='is_confirmed',
            field=models.BooleanField(default=False, verbose_name='Confirmed Conflict'),
        ),
        migrations.AddField(
            model_name='pendingtransaction',
            name='signature',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Transaction Signature'),
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('provider', models.CharField(blank=True, max_length=100, verbose_name='Provider / Bank')),
                ('nominal_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Initial Loan Amount')),
                ('interest_rate', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Interest Rate (%)')),
                ('interest_lock_end', models.DateField(blank=True, null=True, verbose_name='Interest Lock End Date')),
                ('monthly_installment', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monthly Installment')),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='End Date')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('allows_extra_repayment', models.BooleanField(default=False, verbose_name='Extra Repayment Possible')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Loan / Debt',
                'verbose_name_plural': 'Loans / Debts',
            },
        ),
        migrations.CreateModel(
            name='LoanExtraRepayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Amount')),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_repayments', to='finance.loan')),
            ],
            options={
                'verbose_name': 'Extra Repayment',
                'verbose_name_plural': 'Extra Repayments',
                'ordering': ['date'],
            },
        ),
    ]
