# Generated by Django 6.0.2 on 2026-04-07 08:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0019_import_conflict_resolution'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pension',
            name='contribution_end_date',
            field=models.DateField(blank=True, help_text='Date when you stop paying into this pension', null=True, verbose_name='Contribution End Date'),
        ),
        migrations.AddField(
            model_name='pension',
            name='is_indexed',
            field=models.BooleanField(default=True, help_text='If checked, the payout will increase annually based on the global pension increase rate.', verbose_name='Indexed (Inflation Adjustment)'),
        ),
        migrations.AlterField(
            model_name='cashflowsource',
            name='is_inflation_adjusted',
            field=models.BooleanField(default=True, help_text='If checked, the payout will increase annually based on the global pension increase rate.', verbose_name='Indexed (Inflation Adjustment)'),
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('provider', models.CharField(blank=True, max_length=100, verbose_name='Provider / Bank')),
                ('nominal_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Initial Loan Amount')),
                ('interest_rate', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Interest Rate (%)')),
                ('interest_lock_end', models.DateField(blank=True, null=True, verbose_name='Interest Lock End Date')),
                ('monthly_installment', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monthly Installment')),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='End Date')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('allows_extra_repayment', models.BooleanField(default=False, verbose_name='Extra Repayment Possible')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Loan / Debt',
                'verbose_name_plural': 'Loans / Debts',
            },
        ),
        migrations.CreateModel(
            name='LoanExtraRepayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Amount')),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_repayments', to='finance.loan')),
            ],
            options={
                'verbose_name': 'Extra Repayment',
                'verbose_name_plural': 'Extra Repayments',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='PhysicalAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('value', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Current Value')),
                ('appreciation_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Annual Appreciation Rate (%)')),
                ('location', models.CharField(blank=True, max_length=255, verbose_name='Location / Storage')),
                ('storage_costs_monthly', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Monthly Storage/Maintenance Costs')),
                ('is_sold', models.BooleanField(default=False, verbose_name='Is Sold')),
                ('sale_date', models.DateField(blank=True, null=True, verbose_name='Sale Date')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='physical_assets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sachwert (Physical Asset)',
                'verbose_name_plural': 'Sachwerte (Physical Assets)',
            },
        ),
        migrations.CreateModel(
            name='RealEstate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name / Property')),
                ('property_value', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Property Value')),
                ('appreciation_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Annual Appreciation Rate (%)')),
                ('location', models.CharField(blank=True, max_length=255, verbose_name='Location')),
                ('current_tenant', models.CharField(blank=True, max_length=100, verbose_name='Current Tenant')),
                ('rental_income_monthly', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Monthly Rental Income (Net)')),
                ('maintenance_costs_monthly', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Monthly Maintenance/Mgmt Costs')),
                ('ancillary_costs_monthly', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Monthly Ancillary Costs (Nebenkosten)')),
                ('is_sold', models.BooleanField(default=False, verbose_name='Is Sold')),
                ('sale_date', models.DateField(blank=True, null=True, verbose_name='Sale Date')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='real_estates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Immobilie (Real Estate)',
                'verbose_name_plural': 'Immobilien (Real Estate)',
            },
        ),
    ]
